[package]
name = "dup-code-check"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dup-code-check-core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
